server:
  port: 9020
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
management:
  server:
    port: 9020
#    endpoint:
#      shutdown:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
spring:
  application:
    name: QD_Software_Portal
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: validate #create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/qd_software_portal?serverTimezone=UTC #&useSSL=false
    username: qd_software
    password: Psmcg4t1PElyyKs3VHVF]
    initialization-mode: never
    data: classpath*:roles.sql, classpath*:qd_software.sql, classpath*:questionCatalogue.sql, classpath*:customerOrgs.sql
  #  flyway:
  #    locations: classpath:db/migration
  #    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&useSSL=false
  #    user: qd_software
  #    password: pw
  #    schemas: qd_software
  #  h2:
  #    console:
  #      enabled: true
  #  security:
  #    user:
  #      name: Jan
  #      password: password
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 550MB
      max-request-size: 600MB
      enabled: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: asdf
#    password: asdf
#    properties:
#      mail:
#        smpt:
#          port: 25
#          auth: true
#          starttls:
#            enable: true
#            required: true
#  thymeleaf:

logging:
  level:
    root:
      info #debug
    org.hibernate:
      SQL: warn
    web: debug
  file:
    name: logs/qd_software.log
#    path: logs/qd_software.log
#jwt:
#  signing:
#    key:
#      secret: mySecret
#  get:
#    token:
#      uri: /authenticate  # jwt.get.token.uri
#  refresh:
#    token:
#      uri: /refresh       # jwt.refresh.token.uri
#  http:
#    request:
#      header: Authorization
#  token:
#    expiration:
#      in:
#        seconds: 604800