server:
  port: 9020
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
management:
  server:
    port: 9020
#    endpoint:
#      shutdown:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
spring:
  application:
    name: ediportal
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/edi_portal?serverTimezone=UTC&useSSL=false
    username: root
    password: Psmcg4t1PElyyKs3VHVF]
    initialization-mode: always
#  flyway:
#    locations: classpath:db/migration
#    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&useSSL=false
#    user: ediportal
#    password: pw
#    schemas: ediportal
#  h2:
#    console:
#      enabled: true
#  security:
#    user:
#      name: Jan
#      password: password
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 50MB
      max-request-size: 75MB
logging:
  level:
    root:
      info #debug
#jwt:
#  signing:
#    key:
#      secret: mySecret
#  get:
#    token:
#      uri: /authenticate  # jwt.get.token.uri
#  refresh:
#    token:
#      uri: /refresh       # jwt.refresh.token.uri
#  http:
#    request:
#      header: Authorization
#  token:
#    expiration:
#      in:
#        seconds: 604800